polytech_dashboard_home:
    resource: "@PolytechDashboardHomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

Cours:
    path:      /Cours/{id}
    defaults:  { _controller: "PolytechDashboardHomeBundle:Cours:index" }

Note:
    path:      /Note/{id}
    defaults:  { _controller: "PolytechDashboardHomeBundle:Note:index" }