<?php

namespace PolytechDashboard\HomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailNoteRepository extends EntityRepository
{
}
